import React, { useState } from 'react';
import SidebarNav from './components/SidebarNav';
import NexusCore from './components/NexusCore';
import RealityPanel from './components/RealityPanel';
import RouterPanel from './components/RouterPanel';
import LogPanel from './components/LogPanel';
import StatusBar from './components/StatusBar';
import { SROS_MODULE_REGISTRY } from './constants';
import { Menu, ArrowLeft, Hexagon } from 'lucide-react';

const App: React.FC = () => {
  const [selectedModuleId, setSelectedModuleId] = useState<string | null>(null);
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  // Media Generated by the Agent in Nexus Core
  const [agentMedia, setAgentMedia] = useState<{ url: string; type: 'IMAGE' | 'VIDEO' } | null>(null);

  const activeModule = React.useMemo(
    () => SROS_MODULE_REGISTRY.find(m => m.id === selectedModuleId) || null,
    [selectedModuleId]
  );

  const handleModuleSelect = (id: string) => {
    setSelectedModuleId(id);
    setIsSidebarOpen(false);
    // Clear agent media when switching to a module view to focus on simulation
    setAgentMedia(null);
  };

  const clearSelection = () => {
    setSelectedModuleId(null);
  };

  const handleAgentMedia = (url: string, type: 'IMAGE' | 'VIDEO') => {
    setAgentMedia({ url, type });
  };

  const renderMainContent = () => {
    if (selectedModuleId === 'router') {
      return <RouterPanel />;
    }
    if (selectedModuleId === 'logs') {
      return <LogPanel />;
    }
    // Default or other modules
    return <RealityPanel activeModule={activeModule} agentMedia={agentMedia} />;
  };

  return (
    <div className="flex flex-col h-screen w-screen bg-slate-950 text-slate-200 overflow-hidden relative selection:bg-cyan-500/30 font-sans">
      {/* Global Gradient Background */}
      <div className="absolute inset-0 bg-gradient-to-br from-slate-950 via-slate-900 to-indigo-950 z-0" />

      {/* Mobile Header */}
      <div className="md:hidden relative z-50 flex items-center justify-between p-4 border-b border-white/10 bg-slate-900/80 backdrop-blur-md shadow-lg">
        <div className="flex items-center space-x-3">
          <button
            onClick={() => setIsSidebarOpen(true)}
            className="p-2 -ml-2 text-cyan-400 hover:text-cyan-300 hover:bg-white/5 rounded-lg transition-colors"
          >
            <Menu className="w-6 h-6" />
          </button>
          <div className="flex items-center space-x-2">
            <Hexagon className="w-5 h-5 text-cyan-400 fill-cyan-400/10" />
            <span className="font-display font-bold text-white tracking-widest text-sm">SROS NEXUS</span>
          </div>
        </div>
        {activeModule && (
          <button
            onClick={clearSelection}
            className="text-[10px] font-mono text-cyan-400 flex items-center gap-1 border border-cyan-900/50 bg-cyan-950/30 px-3 py-1.5 rounded hover:bg-cyan-900/50 transition-colors"
          >
            <ArrowLeft className="w-3 h-3" /> BACK TO CORE
          </button>
        )}
      </div>

      {/* Main Layout Area */}
      <div className="flex-1 flex relative z-10 overflow-hidden">
        {/* Left: Navigation (Sidebar / Drawer) */}
        <SidebarNav
          selectedModuleId={selectedModuleId}
          onSelectModule={handleModuleSelect}
          isOpen={isSidebarOpen}
          onClose={() => setIsSidebarOpen(false)}
        />

        {/* Middle & Right Content Logic */}

        {/* Nexus Core (Prime Agent) - Always visible on desktop, hidden on mobile if module selected */}
        <div className={`
            flex-shrink-0 border-r border-white/5 bg-slate-900/30 backdrop-blur-sm transition-all duration-300 ease-in-out
            ${activeModule ? 'hidden md:block md:w-[400px] lg:w-[480px]' : 'w-full md:w-[45%] lg:w-[50%]'}
        `}>
          <NexusCore activeModule={activeModule} onAgentMediaGenerated={handleAgentMedia} />
        </div>

        {/* Reality Panel (Holo Deck / Simulation) - Visible on mobile if module selected, or if showing results */}
        <div className={`
            flex-1 bg-black/20 transition-all duration-300
            ${activeModule ? 'block' : 'hidden md:block'}
        `}>
          {renderMainContent()}
        </div>
      </div>

      {/* Footer Status Bar */}
      <StatusBar />
    </div>
  );
};

export default App;